---
- hosts: EC2
  become: yes
  roles:
    - server_preparation
    - docker_install
    - role: mtpproxy
      vars:
        secret: telegram_secret
        data_dir: "/var/docker/MTPproxy/data"
        telegram_port: 4443
    - role: dokuwiki
      vars:
        wiki_host: my_wiki.com
        docker_dir: /var/docker
