---
- hosts: EC2
  become: yes
  tasks:
  - name: Add repository EPEL to amazon linux
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64
  - name: Install pip
    yum:
      name:
        - python2-pip
  - name: Install  docker-py
    pip:
      name:
        - docker-py

  roles:
    - mtpproxy
