---
# install network
- name: Create network
  docker_network:
    name: "{{ dokuwiki_network }}"

# install docker
- name: Pull an image of dokuwiki
  docker_image:
    name: "{{ dokuwiki_image }}"

# install dokuwiki
- name: Create dokuwiki dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ dokuwiki_data_dir }}"
    - "{{ dokuwiki_conf_dir }}"
    - "{{ dokuwiki_plugins_dir }}"
    - "{{ dokuwiki_tpl_dir }}"

- name: Run docker dokuwiki
  docker_container:
    name: "{{ dokuwiki_name }}"
    image: "{{ dokuwiki_image }}"
    networks: 
    - name: "{{ dokuwiki_network }}"
    restart: yes
    restart_policy: always
    volumes:
    - "{{ dokuwiki_data_dir }}:/dokuwiki/data"
    - "{{ dokuwiki_conf_dir }}:/dokuwiki/conf"
    - "{{ dokuwiki_plugins_dir }}:/dokuwiki/lib/plugins"
    - "{{ dokuwiki_tpl_dir }}:/dokuwiki/lib/tpl"

# install nginx
- name: Pull an image of nginx
  docker_image:
    name: "{{ nginx_image }}"

- name: Create nginx dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_conf_dir }}"

- name: Run docker dokuwiki
  docker_container:
    name: "{{ nginx_name }}"
    image: "{{ nginx_image }}"
    networks: 
      - name: "{{ dokuwiki_network }}"
    ports:
      - "{{ nginx_port }}:80"
    restart: yes
    restart_policy: always
    volumes:
    - "{{ nginx_conf_dir }}/{{ wiki_url }}.conf:/etc/nginx/conf.d/{{ wiki_url }}.conf"
