---
docker_dir: "/var/docker"
dokuwiki_network: dokuwiki_network
# nginx
nginx_image: "nginx"
nginx_docker_name: "dokuwiki-nginx-proxy"
nginx_port: 80
nginx_conf_dir: "{{ docker_dir }}/dokuwiki_nginx_proxy"
wiki_url: "my_wiki.com"
# dokuwiki
dokuwiki_image: "mprasil/dokuwiki"
dokuwiki_port: 8080
dokuwiki_docker_name: "dokuwiki"
dokuwiki_dir: "{{ docker_dir }}/dokuwiki"
dokuwiki_data_dir: "{{ dokuwiki_dir }}/data"
dokuwiki_conf_dir: "{{ dokuwiki_dir }}/conf"
dokuwiki_plugins_dir: "{{ dokuwiki_dir }}/lib/plugins"
dokuwiki_tpl_dir: "{{ dokuwiki_dir }}/lib/tpl"